### ISSUE TITLE
using 2 digit year get's interpreted as 21xx

### ISSUE THREAD

**Issue by ordinarygulp** [maubot/reminder#5]
For example

```
!reminder 08-06-19 some reminder

I'll remind you to some reminder at 00:00:00 UTC on Sunday, August 6 2119.
```

**Comment by tulir** [comment]
2 digit years aren't supported anymore and probably won't be in the future either

**Comment by tulir** [comment]
2 digit years are supported now after all (in specific locales, but not the default one)
