### ISSUE TITLE
date is interpreted wrong for timezone

### ISSUE THREAD

**Issue by L0ric0** [maubot/reminder#9]
if the timezone is set to Europe/Berlin the date 05.03.2020 is parsed to the Sunday, May 3 2020 (mm.dd.yyyy) but the convention for that timezone is normaly to parse it to March 5 2020 (dd.mm.yyyy)

**Comment by tulir** [comment]
The timezone only sets the timezone, need a different option for date format locale. I might just replace the parser with something more simple though

**Comment by ndom91** [comment]
Workaround for European Users

in `util.py` on line 14, you can add the following config option to `parser_settings`:

```
"DATE_ORDER": "DMY",
```

Before:
```
parser_settings = {
    "PREFER_DATES_FROM": "future",
    "TIMEZONE": "UTC",
    "TO_TIMEZONE": "UTC",
    "RETURN_AS_TIMEZONE_AWARE": True,
}
```

After:
```
parser_settings = {
    "PREFER_DATES_FROM": "future",
    "TIMEZONE": "UTC",
    "TO_TIMEZONE": "UTC",
    "RETURN_AS_TIMEZONE_AWARE": True,
    "DATE_ORDER": "DMY",
}
```

**Comment by tulir** [comment]
This is no longer a problem since it only allows yyyy-mm-dd. I might add locale support in the future, but it'll be opt-in like time zones instead of everything on by default (which caused conflicts like that).
